USE [master]
GO

/****** Object:  Database [SoundVaultDB]    Script Date: 30/3/2025 00:26:17 ******/
CREATE DATABASE [SoundVaultDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SoundVaultDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SoundVaultDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SoundVaultDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SoundVaultDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SoundVaultDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SoundVaultDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SoundVaultDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SoundVaultDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SoundVaultDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SoundVaultDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SoundVaultDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SoundVaultDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SoundVaultDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SoundVaultDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SoundVaultDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SoundVaultDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SoundVaultDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SoundVaultDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SoundVaultDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SoundVaultDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SoundVaultDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SoundVaultDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SoundVaultDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SoundVaultDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SoundVaultDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SoundVaultDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SoundVaultDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SoundVaultDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SoundVaultDB] SET  MULTI_USER 
GO

ALTER DATABASE [SoundVaultDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SoundVaultDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SoundVaultDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SoundVaultDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SoundVaultDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SoundVaultDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SoundVaultDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SoundVaultDB] SET  READ_WRITE 
GO

